# Default language
en:
  locale: en-us
  contentDir: content/en
  title: "Your Site Title"
  params:
    description: "Site description in English"

# Russian language
ru:
  locale: ru-ru
  contentDir: content/ru
  title: "Название вашего сайта"
  params:
    description: "Описание сайта на русском"
  menu:
    main:
      - name: "О себе"
        url: '#about'
        weight: 1
      - name: "Публикации"
        url: '#publications'
        weight: 2
