ru:
  locale: ru-ru
  contentDir: content/ru
  title: "Мацюк Константин"
  params:
    description: "Описание сайта на русском"
    navbar:
      logo:
        text: "Мацюк Константин"
  menu:
    main:
      - name: "О себе"
        url: '#about'
        weight: 1
      - name: "Публикации"
        url: '#publications'
        weight: 2

en:
  locale: en-us
  contentDir: content/en
  title: "Macyuk Konstantin"
  params:
    description: "Site description in English"
    navbar:
      logo:
        text: "Macyuk Konstantin"
  menu:
    main:
      - name: "Bio"
        url: '#about'
        weight: 1
      - name: "Publications"
        url: '#publications'
        weight: 2
