main:
  - name: О себе
    url: /
    weight: 10
  - name: Публикации
    url: /#papers
    weight: 11
  - name: Доклады
    url: /#talks
    weight: 12
  - name: Новости
    url: /#news
    weight: 13
  - name: Опыт
    url: experience/
    weight: 20
  - name: Проекты
    url: projects/
    weight: 30
  - name: Курсы
    url: courses/
    weight: 40
